services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    
  golang-service:
    container_name: golang-service
    restart: unless-stopped
    user: 1000:1000
    build:
      context: ./middleware
      dockerfile: Dockerfile
    env_file:
      - ./middleware/.env
    ports:
      - "8443:8443"
      - "8883:8883"
    volumes:
      - ./secrets/deploy:/secrets/deploy:ro
