services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./secrets:/secrets
    
  golang-service:
    container_name: golang-service
    restart: unless-stopped
    image: 828171332858.dkr.ecr.ap-southeast-1.amazonaws.com/daviankho/capstone:latest
    environment:
      - CA_CERT=../secrets/devices/devices-ca.crt
      - SERVER_CERT=../secrets/devices/devices-server.crt
      - SERVER_KEY=../secrets/devices/devices-server.key
      - CLIENT_CERT=../secrets/devices/devices-client.crt
      - CLIENT_KEY=../secrets/devices/devices-client.key
      - WS_PORT=8443
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=8883
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    ports:
      - "8443:8443"
    volumes:
      - ./secrets:/secrets:ro
    depends_on:
      - mqtt-broker
