services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    
  golang-service:
    container_name: golang-service
    restart: unless-stopped
    user: 1000:1000
    build:
      context: ./middleware
      dockerfile: Dockerfile
    environment:
      - CA_CERT=../secrets/${MODE}/devices-ca.crt
      - SERVER_CERT=../secrets/${MODE}/devices-server.crt
      - SERVER_KEY=../secrets/${MODE}/devices-server.key
      - CLIENT_CERT=../secrets/${MODE}/devices-client.crt
      - CLIENT_KEY=../secrets/${MODE}/devices-client.key
      - WS_PORT=8443
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=8883
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    ports:
      - "8443:8443"
    volumes:
      - ./secrets:/secrets:ro
    depends_on:
      - mqtt-broker
